notifications:
  email:
    false

dist: trusty
sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "nightly"

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq openjdk-7-jdk

script:
  - python setup.py test
